#!/usr/bin/env bash

VOL=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
MUTE=$(pactl list sinks | grep '^[[:space:]]Mute:' | cut -d':' -f2 | cut -d' ' -f2)

if [[ "$MUTE" == "yes" ]]; then
    echo " $VOL [mute]"
else
    echo " $VOL"
fi

